apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: fowx/cloudproject_database:latest
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: CloudSoftware_#2025!
            - name: MYSQL_DATABASE
              value: clouddatabase
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: database

---

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: dev
  namespace: dev
spec:
  mtls:
    mode: STRICT
