global:
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'your-email@example.com'
  smtp_auth_password: 'your-email-password'

route:
  receiver: email-alert

receivers:
  - name: email-alert
    email_configs:
      - to: 'recipient@example.com'
