groups:
  - name: kubernetes-rules
    rules:
      - alert: PodNotRunning
        expr: kube_pod_status_phase{phase!="Running"} > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Pod '{{ $labels.pod }}' is not running for over 5 minutes"
          description: "Pod '{{ $labels.pod }}' in namespace '{{ $labels.namespace }}' has not been in a running state for over 5 minutes."
