apiVersion: v1
kind: Pod
metadata:
  name: error-logger
  namespace: production
spec:
  containers:
    - name: error-logger
      image: busybox
      command:
        [
          "sh",
          "-c",
          "while true; do echo 'error: something went wrong'; sleep 5; done",
        ]
