apiVersion: v1
kind: Pod
metadata:
  name: pending-test-pod
  namespace: monitoring
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          memory: 1Ti
          cpu: 1
